# ============================================
# Override service classes
parameters:
  cerad_tourn.officials.export_xls.class: 
    Cerad\Bundle\AppBundle\ServicesAdmin\Persons\PersonsExportXLS
    
  cerad_game__project__results__export_xls__class: 
    Cerad\Bundle\AppBundle\Action\Project\Results\Export\ResultsExportXLS
    
  cerad_game__project__results_poolplay__export_xls__class: 
    Cerad\Bundle\AppBundle\Action\Project\Results\Export\ResultsPoolplayExportXLS
    
  cerad_game__project__results_playoffs__export_xls__class: 
    Cerad\Bundle\AppBundle\Action\Project\Results\Export\ResultsPlayoffsExportXLS
    
  cerad_game__project__results_sportsmanship__export_xls__class: 
    Cerad\Bundle\AppBundle\Action\Project\Results\Export\ResultsSportsmanshipExportXLS
    
  cerad_game__game_official__person_name__choice_tpl__class:
    Cerad\Bundle\AppBundle\Action\GameOfficial\Tpl\GameOfficialPersonNameChoiceTpl
    
  cerad_person.aysov_referee_badge.form_type.class: 
    Cerad\Bundle\AppBundle\FormType\AYSO\RefereeBadgeFormType
    
  cerad_game__project__schedule_assignor__show_model_factory__class:
    Cerad\Bundle\AppBundle\Action\Project\Schedule\Assignor\Show\ScheduleAssignorShowModel
    
  cerad_game__project__schedule_assignor__show_form_factory__class:
    Cerad\Bundle\AppBundle\Action\Project\Schedule\Assignor\Show\ScheduleAssignorShowFormFactory
    
services:
    cerad_app.twig_extension:
        class:  Cerad\Bundle\AppBundle\TwigExtension\AppExtension
        arguments:  
            - '%cerad_project_venues%'
            - '@cerad_game__transformer'
            - '@cerad_game__project__game_official__assign_by_assignor__workflow'
            - '@cerad_org__org_key__data_transformer'
        tags:
            - { name: twig.extension }
            
