Cerad\Bundle\GameBundle\Entity\Game:
    type:  entity
    table: games
    repositoryClass: Cerad\Bundle\GameBundle\EntityRepository\GameRepository
    changeTrackingPolicy: NOTIFY

    uniqueConstraints:
       game_project_num_index:
           columns: project_id, num

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            
    oneToMany:
   
       teams:
           targetEntity: GameTeam
           mappedBy:     game
           indexBy:      slot
           cascade:      ['all']
            
       officials:
           targetEntity: GameOfficial
           mappedBy:     game
           indexBy:      slot
           cascade:      ['all']     
    
    manyToOne:
                
        field:
            targetEntity: GameField
            nullable:     false
      
    fields:
            
        projectId:
            column:   project_id
            type:     string
            length:   80
            nullable: false
          
        num:
            column:   num
            type:     integer
            nullable: false
            
        role:
            column:   role
            type:     string
            length:   20
            nullable: false
            
        levelId:
            column:   level_id
            type:     string
            length:   80
            nullable: true
            
        group:
            column:   groupx
            type:     string
            length:   20
            nullable: true
            
        groupType:
            column:   groupx_type
            type:     string
            length:   20
            nullable: true
                    
        dtBeg:
            column:   dt_beg
            type:     datetime
            nullable: false
            
        dtEnd:
            column:   dt_end
            type:     datetime
            nullable: true      # Maybe a TBD or BYE flag?
            
        orgId:
            column:   org_id
            type:     string
            length:   80
            nullable: true
                      
        status:
            column:   status
            type:     string
            length:   20
            nullable: false
            
        link:
            column:   link
            type:     integer
            nullable: true
            
        report:
            column:   report
            type:     array
            nullable: true
            