# ====================================
# Bunch of levels

AYSO_VIP_Extra:
    name:      VIP_Extra
    div:       Extra
    age:       VIP
    gender:    VIP
    sport:     Soccer
    domain:    AYSO
    domainSub: AYSO

AYSO_U10B_Extra:
    name:      U10B_Extra
    div:       Extra
    age:       U10
    gender:    B
    sport:     Soccer
    domain:    AYSO
    domainSub: AYSO
        
AYSO_U10G_Extra:
    name:      U10G_Extra
    div:       Extra
    age:       U10
    gender:    G
    sport:     Soccer
    domain:    AYSO
    domainSub: AYSO
    
AYSO_U12B_Extra:
    name:      U12B_Extra
    div:       Extra
    age:       U12
    gender:    B
    sport:     Soccer
    domain:    AYSO
    domainSub: AYSO
        
AYSO_U12G_Extra:
    name:      U12G_Extra
    div:       Extra
    age:       U12
    gender:    G
    sport:     Soccer
    domain:    AYSO
    domainSub: AYSO
    
AYSO_U14B_Extra:
    name:      U14B_Extra
    div:       Extra
    age:       U14
    gender:    B
    sport:     Soccer
    domain:    AYSO
    domainSub: AYSO
        
AYSO_U14G_Extra:
    name:      U14G_Extra
    div:       Extra
    age:       U14
    gender:    G
    sport:     Soccer
    domain:    AYSO
    domainSub: AYSO
        
AYSO_U16B_Extra:
    name:      U16B_Extra
    div:       Extra
    age:       U16
    gender:    B
    sport:     Soccer
    domain:    AYSO
    domainSub: AYSO
        
AYSO_U16G_Extra:
    name:      U16G_Extra
    div:       Extra
    age:       U16
    gender:    G
    sport:     Soccer
    domain:    AYSO
    domainSub: AYSO
        
AYSO_U19B_Extra:
    name:      U19B_Extra
    div:       Extra
    age:       U19
    gender:    B
    sport:     Soccer
    domain:    AYSO
    domainSub: AYSO
        
AYSO_U19G_Extra:
    name:      U19G_Extra
    div:       Extra
    age:       U19
    gender:    G
    sport:     Soccer
    domain:    AYSO
    domainSub: AYSO
        
