imports:
    - { resource: parameters.yml }
    - { resource: security.yml   }
    - { resource: doctrine.yml   }
    - { resource: projects.yml   }
    - { resource: projectACL.yml }
    - { resource: levels.yml     }
    - { resource: venues.yml     }
    - { resource: pools.yml      }
    - { resource: show.yml       }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
        # Wordpress paths        
        packages:
          NG2014:
            base_urls: ["http://2014nationalgames.org/"]
          refLogin:
            base_urls: ["http://2014nationalgames.org/ref_register/"]    
                
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         
        name:        zayso_session
        save_path: "%kernel.root_dir%/sessions"
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    paths:
        "%kernel.root_dir%/../src/Cerad/Bundle/AppBundle/Resources/views":      CeradTourn
        "%kernel.root_dir%/../src/Cerad/Bundle/AppBundle/Resources/viewsAdmin": CeradTournAdmin
        #
        "%kernel.root_dir%/../src/Cerad/Bundle/AppBundle/Resources/views/CeradGame": CeradGame
        "%kernel.root_dir%/../../cerad2/src/Cerad/Bundle/GameBundle/Action":         CeradGame
        #
        "%kernel.root_dir%/../src/Cerad/Bundle/AppBundle/Resources/views/CeradPerson": CeradPerson
        "%kernel.root_dir%/../../cerad2/src/Cerad/Bundle/PersonBundle/Action":         CeradPerson
    
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration - moved to doctrine.yml

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    disable_delivery: %mailer_disable_delivery%
# Needed to comment this out to get the monolog email working
#   spool:     { type: memory }
