#!/bin/bash
php console cache:clear --env=prod --no-debug
php console assets:install ~/public_html/natgames2014
php console assets:install ~/public_html/natgames2014x
php console assetic:dump   ~/public_html/natgames2014
php console assetic:dump   ~/public_html/natgames2014x
