#!/bin/bash
php console cache:clear --env=dev --no-debug
php console assets:install ../../zayso/web/natgames2014
php console assets:install ../../zayso/web/natgames2014x
php console assetic:dump   ../../zayso/web/natgames2014
php console assetic:dump   ../../zayso/web/natgames2014x
