# =================================================
# Top pages
cerad_tourn_index:
    pattern:  /
    defaults: { _controller: CeradTournBundle:Tourn/TournIndex:index }
#   redirect: cerad_tourn_welcome

cerad_tourn_welcome:
    pattern:  /welcome
    defaults: { _controller: CeradTournBundle:Tourn/TournWelcome:welcome }
#                           @CeradTourn/Tourn/Welcome/TournWelcomeIndex.html.twig
    
cerad_tourn_home:
    pattern:  /home
    defaults: { _controller: CeradTournBundle:Tourn/TournHome:home }
#                           @CeradTourn/Tourn/Home/TournHomeIndex.html.twig
    
cerad_tourn_contact:
    pattern:  /contact
    defaults: { _controller: CeradTournBundle:Tourn/TournContact:contact }
#                           @CeradTourn/Tourn/Contact/TournContactIndex.html.twig

cerad_tourn_help:
    pattern:  /help
    defaults: { _controller: CeradTournBundle:Tourn/TournHelp:help }
#                           @CeradTourn/Tourn/Home/TournHomeIndex.html.twig

cerad_tourn_test:
    pattern:  /test
    defaults: { _controller: CeradTournBundle:Tourn/TournTest:test }
#                           @CeradTourn/Tourn/Test/TournTestIndex.html.twig

# ========================================================================
# Accounts

cerad_tourn_account_create:
    pattern:  /account/create
    defaults: { _controller: CeradTournBundle:Account/AccountCreate:create }
#               _template    CeradTourn/Account/Create/AccountCreateIndex.html.twig
#                                                     /AccountCreateForm.html.twig
#                                                     /AccountCreateHelp.html.twig
#               _service     cerad_user.user_manager
#               _service     cerad_person.person_repository

cerad_tourn_account_update:
    pattern:  /account/update
    defaults: { _controller: CeradTournBundle:Account/AccountUpdate:update }
#                           @CeradTourn/Account/Update/AccountUpdateIndex.html.twig
#                                                     /AccountUpdateForm.html.twig
#                                                     /AccountUpdateHelp.html.twig

cerad_tourn_accounts_list:
    pattern:  /accounts/list
    defaults: { _controller: CeradTournBundle:Accounts/AccountsList:list }
#                           @CeradTourn/Accounts/List/AccountsListIndex.html.twig
    
# =======================================
# So should this be account password or user password?
cerad_tourn_account_password_reset_request:
    pattern:  /account-password/reset-request
    defaults: { _controller: CeradTournBundle:AccountPassword/AccountPasswordResetRequest:request }
#                           @CeradTourn/AccountPassword/ResetRequest/AccountPasswordResetRequestIndex.html.twig
#                                                                   /AccountPasswordResetRequestForm.html.twig
#                                                                   /AccountPasswordResetRequestUpdateHelp.html.twig
    
cerad_tourn_account_password_reset_requested:
    pattern:  /account-password/reset-requested/{id}/{token}
    defaults: { _controller: CeradTournBundle:AccountPassword/AccountPasswordResetRequested:requested, id: null, token: null }
#                           @CeradTourn/AccountPassword/ResetRequested/AccountPasswordResetRequestedIndex.html.twig
#                                                                     /AccountPasswordResetRequestedForm.html.twig
#                                                                     /AccountPasswordResetRequestedUpdateHelp.html.twig
    
# ==================================================================
# login/logout stuff works on a resource called user
# 
cerad_tourn_account_user_login:
    pattern:  /account-user/login
    defaults: { _controller: CeradTournBundle:AccountUser/AccountUserLogin:login }
#                           @CeradTourn/AccountUser/AccountUserLoginIndex.html.twig
#                                                  /AccountUserLoginForm.html.twig
#                                                  /AccountUserLoginHelp.html.twig
cerad_tourn_account_user_login_check:
    pattern:  /account-user/check
    
cerad_tourn_account_user_logout:
    pattern:  /account-user/logout

# Alias for: cerad_tourn_account_user_login
cerad_tourn_user_login:
    pattern:  /login
    defaults: { _controller: CeradTournBundle:AccountUser/AccountUserLogin:login }
    
cerad_tourn_user_login_check:
    pattern:  /account-user/check
    
cerad_tourn_user_logout:
    pattern:  /account-user/logout

# ==================================
# Person Stuff

cerad_tourn_person_create:
    pattern:  /person/create
    defaults: { _controller: CeradTournBundle:Person/PersonCreate:create }
#                           @CeradTourn/Person/Create/PersonCreateIndex.html.twig
#                                                    /PersonCreateForm.html.twig
#                                                    /PersonCreateHelp.html.twig
   
cerad_tourn_person_update:
    pattern:  /person/update/{id}
    defaults: { _controller: CeradTournBundle:Person/PersonUpdate:update, id: 0 }
#                           @CeradTourn/Person/Update/PersonUpdateIndex.html.twig
#                                                    /PersonUpdateForm.html.twig
#                                                    /PersonUpdateHelp.html.twig
    
cerad_tourn_persons_list:
    pattern:  /persons/list
    defaults: { _controller: CeradTournBundle:Persons/PersonsList:list }
#                           @CeradTourn/Persons/List/PersonsListIndex.html.twig

#
cerad_tourn_person_person_create:
    pattern:  /person-person/create
    defaults: { _controller: CeradTournBundle:PersonPerson/PersonPersonCreate:create }
#                           @CeradTourn/PersonPerson/Create/PersonPersonCreateIndex.html.twig
#                                                          /PersonPersonCreateForm.html.twig
#                                                          /PersonPersonCreateHelp.html.twig
    
cerad_tourn_person_person_update:
    pattern:  /person-person/update/{id}
    defaults: { _controller: CeradTournBundle:PersonPerson/PersonPersonUpdate:update, id : 0 }
#                           @CeradTourn/PersonPerson/Update/PersonPersonUpdateIndex.html.twig
#                                                          /PersonPersonUpdateForm.html.twig
#                                                          /PersonPersonUpdateHelp.html.twig
    
cerad_tourn_person_persons_list:
    pattern:  /person-persons/list
    defaults: { _controller: CeradTournBundle:PersonPersons/PersonPersonsList:list }
#                           @CeradTourn/PersonPersons/List/PersonPersonsListIndex.html.twig
    
# 
cerad_tourn_person_plan_update:
    pattern:  /person-plan/update/{id}
    defaults: { _controller: CeradTournBundle:PersonPlan/PersonPlanUpdate:update, id : 0 }
#                           @CeradTourn/PersonPlan/Update/PersonPlanUpdateIndex.html.twig
#                                                        /PersonPlanUpdateForm.html.twig
#                                                        /PersonPlanUpdateHelp.html.twig
# ===============================================
# Schedule and results
cerad_tourn_schedule_official_list:
    pattern:  /schedule/official.{_format}
    defaults: 
        _controller: CeradTournBundle:Schedule/ScheduleOfficialList:list
        _template: '@CeradTourn/Schedule/Official/ScheduleOfficialIndex.html.twig'
        _format: html
    requirements:
        _format:  html|csv|xls|pdf
        
cerad_tourn_schedule_officials:
    pattern:  /schedule/officials.{_format}
    defaults: 
        _controller: CeradAppBundle:Schedule/ScheduleOfficialList:list
        _template: '@CeradApp/Schedule/Official/List/ScheduleOfficialIndex.html.twig'
        _format: html
        _role: ROLE_ADMIN
    requirements:
        _format:  html|csv|xls|pdf
        
# ==========================================
# _controller is a service
# DI is used to inject model into the controller's constructor
# TODO: Have a listener create the model and pass via the action
cerad_tourn.game_official.user_assign_slot:
    pattern:  /game-official/user-assign-slot/{game}/{slot}
    defaults:
        _controller: cerad_tourn.game_official.user_assign_slot.controller:assignAction
        _model:      cerad_tourn.game_official.user_assign_slot.model
        _template: '@CeradTourn/GameOfficial/UserAssignSlot/UserAssignSlotIndex.html.twig'
        _redirect:   cerad_tourn_schedule_official_list
        _role:       ROLE_USER
        game: 0
        slot: 0
        
cerad_tourn_schedule_team_list:
    pattern:  /schedule/team
    defaults: { _controller: CeradTournBundle:Schedule/ScheduleTeamList:list }
    
cerad_tourn_schedule_my_list:
    pattern:  /schedule/my
    defaults: { _controller: CeradTournBundle:Schedule/ScheduleMyList:list }
    
cerad_tourn_game_update:
    pattern:  /game/update
    defaults: { _controller: CeradTournBundle:Game/GameUpdate:update }
  
cerad_tourn_game_report_update:
    pattern:  /game-report/update/{num}
    defaults: { _controller: CeradTournBundle:GameReport/GameReportUpdate:update }

cerad_tourn_results_poolplay:
    pattern:  /results/poolplay
    defaults: { _controller: CeradTournBundle:Results/PoolPlayResults:results }
  
# ===============================================
# Internal controllers
# header:
#   defaults: { _controller: CeradTournBundle:Tourn/Header/TournHeader:render }
#                            CeradTourn/Tourn/Header/TournHeaderIndex.html.twig

# =============================================================================
# Got this far then it must be a slug type deal

#cerad_tourns_index:
#    pattern:  /{slug}
#    defaults: { _controller: CeradTournBundle:Tourns/TournsIndex:index }
    
#cerad_tourns_welcome:
#    pattern:  /{slug}/welcome
#    defaults: { _controller: CeradTournBundle:Tourns/TournsWelcome:welcome }

 