Cerad\Bundle\PersonBundle\Entity\PersonPerson:
    type:  entity
    table: person_persons
    repositoryClass: Cerad\Bundle\PersonBundle\EntityRepository\PersonPersonRepository
    
    changeTrackingPolicy: NOTIFY
    
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            
    manyToOne:
        parent:
            targetEntity: Person
            inversedBy:   persons
        child:
            targetEntity: Person

    fields:      
        role:
            column:   role
            type:     string
            length:   20
            nullable: false

        verified:
            type:     string
            length:   20
            nullable: true
            
        status:
            type:     string
            length:   20
            nullable: false
