    
cerad_person__project__person_teams__show:
    path:  /project/{_project}/person/{_person}/teams
    defaults: 
        _controller: cerad_person__project__person_teams__show_controller:action
        _model:      cerad_person__project__person_teams__show_model_factory
        _form:       cerad_person__project__person_teams__show_form_factory
        _template: '@CeradPerson\Project\PersonTeams\Show\PersonTeamsShowTwigPage.html.twig'
        _userPerson: required
        
cerad_person__project__person_persons__show:
    path:  /project/{_project}/person/{_person}/persons
    defaults: 
        _controller: cerad_person__project__person_persons__show_controller:action
        _model:      cerad_person__project__person_persons__show_model_factory
        _form:       cerad_person__project__person_persons__show_form_factory
        _template: '@CeradPerson\Project\PersonPersons\Show\PersonPersonsShowTwigPage.html.twig'
        _userPerson: required
        
cerad_person__project__persons__show:
    path:  /project/{_project}/persons/show
    defaults: 
        _controller: cerad_person__project__persons__show_controller:action
        _model:      cerad_person__project__persons__show_model_factory
        _form:       cerad_person__project__persons__show_form_factory
        _template: '@CeradPerson\Project\Persons\Show\PersonsShowTwigPage.html.twig'
        _role_:      ROLE_ADMIN
