parameters:
  
services:
  # =======================================================================
  # Action: Project Persons Show
  #
  cerad_person__project__persons__show_model_factory:
    class: Cerad\Bundle\PersonBundle\Action\Project\Persons\Show\PersonsShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_person__person_repository'
      - '@cerad_person__project_person__repository'
      - '@cerad_user__user_repository'
      - '@cerad_org__org_key__data_transformer'
      - '@cerad_core__role_hierarchy'
      - '%security.role_hierarchy.roles%'
      
  cerad_person__project__persons__show_form_factory:
    class: Cerad\Bundle\PersonBundle\Action\Project\Persons\Show\PersonsShowFormFactory
    arguments:
      - '%security.role_hierarchy.roles%'

    calls:
      - [setRouter,      ['@router']]
      - [setFormFactory, ['@form.factory']]
      - [setDispatcher,  ['@event_dispatcher']]
             
  cerad_person__project__persons__show_controller:
    class: Cerad\Bundle\PersonBundle\Action\Project\Persons\Show\PersonsShowController
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
